<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-T7322OL" name="FirefoxTest" tests="1" failures="0" timestamp="4 Apr 2018 03:29:24 GMT" time="0.285" errors="0">
  <testcase name="@BeforeTest beforeTest" time="0.0" classname="sample.Cross">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1
	at utility.ReadORFile.getLocator(ReadORFile.java:37)
	at sample.Cross.beforeTest(Cross.java:28)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeTest beforeTest -->
  <testcase name="@AfterTest afterTest" time="0.0" classname="sample.Cross">
    <skipped/>
  </testcase> <!-- @AfterTest afterTest -->
  <testcase name="gmail" time="0.01" classname="sample.Cross">
    <skipped/>
  </testcase> <!-- gmail -->
</testsuite> <!-- FirefoxTest -->
